name: Blackduck SCA Scan # Name of the workflow
on:
  push:  # Trigger the workflow on push events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on push
  pull_request:  # Trigger the workflow on pull request events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on PR

jobs:
  build:  # Define a job named 'build'
    #runs-on: [sh_mac_mdn]  # Specify the runner to execute the job
    runs-on: [self-hosted]  # Specify the runner to execute the job
    #runs-on: self-hosted
    steps:  # List of steps to execute in this job
      - name: Checkout Source  # Step to check out the repository code
        uses: actions/checkout@v4  # Use the checkout action to clone the repo
      - name: Black Duck SCA Full Scan  # Step for running a full Black Duck scan
        id: black-duck-full-scan  # Unique ID for this step
        uses: blackduck-inc/black-duck-security-scan@v2.9.0 # Use the Black Duck security scan action
        #uses: blackduck-inc/black-duck-security-scan@SIGINT-3342
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}  # Set project name based on repo name
          #BRIDGE_DETECT_ARGS: " "
           # NO_PROXY: 'repo.blackduck.com, artifactory.tools.duckutil.net'
           # HTTPS_PROXY: ${{ secrets.PROXY }}
           
          
        with:
          #blackducksca_externalIssues_create: true
          #blackducksca_externalIssues_severities: "Low"
          #blackducksca_externalIssues_groupSCAIssues: false
          #blackducksca_externalIssues_maxCount: 3
  
          detect_install_directory: '/Users/madhavanr/bd-detect'  # Specify the installation directory for Black Duck Detect 
          detect_args: '--detect.diagnostic=true'
          #detect_args: '--detect.diagnostic=true'
          #bridgecli_download_url: "https://repo.blackduck.com/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/3.9.2/bridge-cli-bundle-3.9.2-macos_arm.zip"
          #bridgecli_download_url: https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/4.1.1rc1/bridge-cli-bundle-4.1.1rc1-macos_arm.zip  
          #bridgecli_download_url: "https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.10.1rc3//bridge-cli-bundle-3.10.1rc3-macos_arm.zip"
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}  # Black Duck server URL from environment variables
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}  # Black Duck API token from secrets
          #network_ssl_trustAll: true
          #blackducksca_scan_full: false  # Perform a full scan
          #blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'  # Specify severities for scan failures
          #blackducksca_waitForScan: false
          blackducksca_reports_sarif_create: true
          #blackducksca_reports_sarif_severities: 'High'
          blackducksca_upload_sarif_report: true
          #Fix PR Config
          #blackducksca_fixpr_enabled: true
          #blackducksca_fixpr_maxCount: 3
          
          b#lackducksca_fixpr_filter_severities: 'CRITICAL,HIGH'
          #blackducksca_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
          github_token: ${{ secrets.BD_GITHUB_TOKEN }}  # GitHub token for authentication when posting comment
          blackducksca_prComment_enabled: true  # Enable automatic PR comments based on scan results
          #github_token: ${{ secrets.BD_GITHUB_TOKEN }}  # GitHub token for authentication when posting comments
          #mark_build_status: 'success' # Mark build status as failure if issues are found
          
    
    
          
